version: "3.9"
services: 
  api:
    build: ./apiFileUpload
    command: python manage.py runserver 0.0.0.0:8000
    ports: 
      - "8000:8000"
    restart: "always"
  web:
    build: ./frontend
    ports: 
      - "80:80"
    restart: "always"  
    
